Repository 2023OpenSourceProject/project, pull requests merged in 2023-12, with the labels that each got.

#75 댓글, 리뷰 CRUD 개발
  backend/src/main/java/site/travellog/travellog/controller/CommentController.java
  backend/src/main/java/site/travellog/travellog/controller/ReviewController.java
  backend/src/main/java/site/travellog/travellog/controller/UserController.java
  backend/src/main/java/site/travellog/travellog/domain/Review.java
  backend/src/main/java/site/travellog/travellog/dto/CommentDto.java
  backend/src/main/java/site/travellog/travellog/dto/ReviewDto.java
  backend/src/main/java/site/travellog/travellog/repository/CommentRepository.java
  backend/src/main/java/site/travellog/travellog/service/CommentService.java
  backend/src/main/java/site/travellog/travellog/service/ReviewService.java
  backend/src/main/java/site/travellog/travellog/service/UserService.java
  frontend/src/components/Account/RegisterForm.jsx
  frontend/src/components/Mypage/MyReview.jsx
  frontend/src/components/Mypage/MyReview.module.css
  frontend/src/components/TravelReview/ReadReview.jsx
  frontend/src/components/TravelReview/ReadReview.module.css
Labels: BE, FE, Refactor

#76 리뷰 수정 기능 추가
  frontend/src/App.jsx
  frontend/src/components/Mypage/MyReview.jsx
  frontend/src/components/Mypage/MyReview.module.css
  frontend/src/components/TravelReview/EditReview.jsx
  frontend/src/components/TravelReview/ReadReview.jsx
  frontend/src/components/TravelReview/ReadReview.module.css
Labels: FE, Feature

#77 65/UI 수정
  frontend/src/App.css
  frontend/src/assets/addBtn.svg
  frontend/src/assets/image/noResult2.png
  frontend/src/assets/image/notFound.svg
  frontend/src/components/Plan/CreateMap.jsx
  frontend/src/components/Plan/NewPlan.module.css
  frontend/src/components/Plan/TravelList.jsx
  frontend/src/components/UI/ModalComponent.jsx
  frontend/src/components/UI/ModalComponent.module.css
  frontend/src/components/UI/Navbar.css
Labels: FE, Refactor

#79 73/마이페이지 왼쪽 바, 리뷰리스트 공백 시 페이지 수정
  frontend/src/components/Mypage/MyReview.module.css
  frontend/src/components/Mypage/MyReviewList.jsx
  frontend/src/components/Mypage/MyReviewList.module.css
  frontend/src/components/Mypage/MySideBar.jsx
  frontend/src/components/Mypage/MySideBar.module.css
  frontend/src/components/Mypage/Mypage.jsx
  frontend/src/components/Mypage/Setting.jsx
  frontend/src/components/Mypage/Setting.module.css
  frontend/src/components/TravelReview/ReadReview.module.css
  frontend/src/components/TravelReview/ReviewList.jsx
  frontend/src/components/TravelReview/ReviewList.module.css
Labels: FE, Refactor

#80 65/UI 수정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/selectedIcon.svg
  frontend/src/components/Plan/CreateMap.jsx
  frontend/src/components/Plan/NewPlan.module.css
  frontend/src/components/Plan/PlanNavbar.module.css
  frontend/src/components/Plan/TravelList.jsx
  frontend/src/components/Plan/TravelList.module.css
  frontend/src/components/TravelReview/ReadReview.jsx
  frontend/src/components/TravelReview/ReadReview.module.css
  frontend/src/components/UI/ModalComponent.jsx
  frontend/src/components/UI/ModalComponent.module.css
Labels: FE, Refactor

#83 BE) view plan을 할때 token이 필요 없이로 변경 (#82)
  backend/src/main/java/site/travellog/travellog/controller/PlanController.java
  backend/src/main/java/site/travellog/travellog/global/security/SecurityConfig.java
  backend/src/main/java/site/travellog/travellog/service/PlanService.java
Labels: BE, Refactor

#86 console.log 삭제(#74)
  frontend/src/components/MainPage.jsx
  frontend/src/components/Mypage/MyReviewList.jsx
  frontend/src/components/Mypage/Mypage.jsx
  frontend/src/components/Mypage/Setting.jsx
  frontend/src/components/Plan/CreateMap.jsx
  frontend/src/components/Plan/NewPlan.jsx
  frontend/src/components/Plan/PlanNavbar.jsx
  frontend/src/components/TravelReview/NewReview.jsx
  frontend/src/components/TravelReview/ReadReview.jsx
  frontend/src/components/TravelReview/ReviewList.jsx
  frontend/src/components/UI/Navbar.css
Labels: FE, Refactor

#88 네비게이션 바 디자인 개선(#84)
  frontend/src/components/UI/Navbar.css
  frontend/src/components/UI/Navbar.jsx
Labels: FE, Refactor

#90 색 디자인 개선(#84)
  frontend/src/assets/image/accountImage2.png
  frontend/src/components/Account/AccountForm.module.css
  frontend/src/components/Account/FindPwdForm.jsx
  frontend/src/components/Account/LoginForm.jsx
  frontend/src/components/Account/RegisterForm.jsx
  frontend/src/components/MainPage.module.css
  frontend/src/components/Mypage/MyReviewList.module.css
  frontend/src/components/Mypage/MySideBar.module.css
  frontend/src/components/Mypage/Setting.module.css
  frontend/src/components/TravelReview/NewReview.module.css
  frontend/src/components/TravelReview/ReadReview.module.css
  frontend/src/components/TravelReview/ReviewList.module.css
  frontend/src/components/UI/Navbar.css
Labels: FE, Refactor

#91 87/마이페이지 내 계획 리스트 구현
  frontend/src/components/Mypage/MyPlan.jsx
  frontend/src/components/Mypage/MyPlan.module.css
  frontend/src/components/Mypage/MyPlanList.jsx
  frontend/src/components/Mypage/MyPlanList.module.css
  frontend/src/components/Mypage/MyReview.jsx
  frontend/src/components/Mypage/MySideBar.jsx
  frontend/src/components/Mypage/Mypage.jsx
Labels: FE, Feature

#93 내 게시물만 삭제 가능하도록(#84)
  frontend/src/components/Mypage/MyPlan.jsx
  frontend/src/components/TravelReview/ReadReview.jsx
Labels: FE, Refactor

#94 81/리뷰페이지 플랜 내용 UI Refactor
  frontend/src/components/TravelReview/PlanDetails.jsx
  frontend/src/components/TravelReview/PlanDetails.module.css
Labels: FE, Feature

#95 81/리뷰 페이지 UI 수정
  frontend/src/assets/arrowIcon.png
  frontend/src/assets/locationIcon/Accomodation.png
  frontend/src/assets/locationIcon/Cafe.png
  frontend/src/assets/locationIcon/ConvenienceStore.png
  frontend/src/assets/locationIcon/DepartmentStore.png
  frontend/src/assets/locationIcon/Hospital.png
  frontend/src/assets/locationIcon/Restaurant.png
  frontend/src/assets/locationIcon/School.png
  frontend/src/assets/locationIcon/Transpotation.png
  frontend/src/assets/locationIcon/default.png
  frontend/src/components/TravelReview/EditReview.jsx
  frontend/src/components/TravelReview/NewReview.jsx
  frontend/src/components/TravelReview/PlanDetails.jsx
  frontend/src/components/TravelReview/PlanDetails.module.css
  frontend/src/components/TravelReview/ReadReview.jsx
  frontend/src/components/TravelReview/ReviewList.module.css
  frontend/src/components/UI/Footer.jsx
  frontend/src/components/UI/Footer.module.css
Labels: FE, Feature, Refactor

#99 96/Plan 페이지 UI 수정
  frontend/src/components/Plan/NewPlan.module.css
  frontend/src/components/Plan/TravelList.jsx
  frontend/src/components/Plan/TravelList.module.css
Labels: FE, Refactor

#100 92/긴급수정
  frontend/src/components/Plan/CreateMap.jsx
Labels: FE, Refactor

#101 65/플랜 생성 페이지 수정
  frontend/src/assets/arrow_downward_alt.svg
  frontend/src/components/Plan/NewPlan.module.css
  frontend/src/components/Plan/TravelList.jsx
  frontend/src/components/Plan/TravelList.module.css
Labels: FE, Refactor

#103 92/내 계획 Read 기능 추가 및 지도관련 오류 해결
  frontend/src/App.jsx
  frontend/src/components/Mypage/MyPlan.jsx
  frontend/src/components/Mypage/MyPlan.module.css
  frontend/src/components/Mypage/MyPlanList.jsx
  frontend/src/components/Mypage/MyPlanMap.jsx
  frontend/src/components/Mypage/MyPlanNavbar.jsx
  frontend/src/components/Mypage/MyPlanNavbar.module.css
  frontend/src/components/Mypage/MyTravelList.jsx
  frontend/src/components/Mypage/MyTravelList.module.css
  frontend/src/components/Mypage/Mypage.jsx
  frontend/src/components/Plan/CreateMap.jsx
Labels: FE, Feature, 🚨 우선 순위 높음

#104 84/호버 기능 추가
  frontend/src/components/Plan/NewPlan.module.css
  frontend/src/components/Plan/PlanNavbar.module.css
  frontend/src/components/Plan/TravelList.module.css
  frontend/src/components/UI/ModalComponent.module.css
Labels: FE, Refactor

#98 BE) 카테고리 추가 (#78)
  backend/src/main/java/site/travellog/travellog/domain/PlanDetail.java
  backend/src/main/java/site/travellog/travellog/dto/PlanDetailDto.java
  backend/src/main/java/site/travellog/travellog/service/PlanService.java
Labels: BE, Refactor

#106 84/refactor
  frontend/src/components/Mypage/MyPlanNavbar.module.css
  frontend/src/components/Mypage/Setting.module.css
  frontend/src/components/Plan/NewPlan.module.css
  frontend/src/components/Plan/PlanNavbar.module.css
  frontend/src/components/TravelReview/NewReview.module.css
Labels: FE, Refactor

#107 92/MyPlan 페이지 마커번호 및 점선 연결 구현
  frontend/src/components/Mypage/MyPlanMap.jsx
Labels: FE, Feature

#108 65/최종 UI 수정, 플랜 페이지 오버레이 기능 추가, 오류 수정
  frontend/index.html
  frontend/src/App.css
  frontend/src/assets/travelLog.png
  frontend/src/components/MainPage.module.css
  frontend/src/components/Mypage/MyPlan.module.css
  frontend/src/components/Mypage/MyPlanList.module.css
  frontend/src/components/Mypage/MyPlanMap.jsx
  frontend/src/components/Mypage/MyPlanNavbar.jsx
  frontend/src/components/Mypage/MyPlanNavbar.module.css
  frontend/src/components/Mypage/MyReview.jsx
  frontend/src/components/Mypage/MyReview.module.css
  frontend/src/components/Mypage/MyReviewList.module.css
  frontend/src/components/Mypage/MySideBar.module.css
  frontend/src/components/Mypage/MyTravelList.module.css
  frontend/src/components/Mypage/Setting.module.css
  frontend/src/components/Plan/CreateMap.jsx
  frontend/src/components/Plan/NewPlan.module.css
  frontend/src/components/Plan/PlanNavbar.jsx
  frontend/src/components/Plan/PlanNavbar.module.css
  frontend/src/components/Plan/TravelList.jsx
  frontend/src/components/Plan/TravelList.module.css
  frontend/src/components/TravelReview/NewReview.jsx
  frontend/src/components/TravelReview/NewReview.module.css
  frontend/src/components/TravelReview/PlanDetails.module.css
  frontend/src/components/TravelReview/ReadReview.jsx
  frontend/src/components/TravelReview/ReadReview.module.css
  frontend/src/components/TravelReview/ReviewList.module.css
  frontend/src/components/UI/Footer.module.css
  frontend/src/components/UI/ModalComponent.jsx
  frontend/src/components/UI/ModalComponent.module.css
  frontend/src/components/UI/Navbar.jsx
  frontend/src/components/UI/Overlay.css
Labels: FE, Feature, Refactor

#110 109/긴급수정
  frontend/src/components/Plan/CreateMap.jsx
  frontend/src/components/TravelReview/NewReview.jsx
Labels: FE, 🚨 우선 순위 높음, Refactor
