Repository 2023OpenSourceProject/project, pull requests merged in 2023-11, with the labels that each got.

#4 메인 페이지 html 요소 추가 및 CSS 적용
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/image/mainPageImage.png
  frontend/src/components/MainPage.jsx
  frontend/src/components/MainPage.module.css
  frontend/src/index.css
Labels: FE, Feature

#9 8/프론트엔드 기본 컴포넌트 트리 구조 파일들 미리 생성함 버튼 UI JSX 파일 생성
  frontend/src/components/Account/Account.jsx
  frontend/src/components/Account/FindPwdForm.jsx
  frontend/src/components/Account/LoginForm.jsx
  frontend/src/components/Account/RegisterForm.jsx
  frontend/src/components/Mypage/Mypage.jsx
  frontend/src/components/Plan/CreateMap.jsx
  frontend/src/components/Plan/NewPlan.jsx
  frontend/src/components/Plan/PlanNavbar.jsx
  frontend/src/components/Plan/useKakaoLoader.jsx
  frontend/src/components/TravelReview/NewReview.jsx
  frontend/src/components/TravelReview/ReadReview.jsx
  frontend/src/components/TravelReview/ReviewList.jsx
  frontend/src/components/UI/Button.jsx
  frontend/src/components/UI/Button.module.css
  frontend/src/components/UI/NotFound.jsx
Labels: FE

#10 5/네비게이션 바 요소 추가 및 CSS 적용
  frontend/src/components/UI/Navbar.css
  frontend/src/components/UI/Navbar.jsx
Labels: FE, Feature

#12 11/테스트css파일삭제 버그수정
  frontend/src/components/MainPage.jsx
Labels: FE, Refactor

#16 13/플랜 페이지 기본 디자인 틀 구현
  frontend/index.html
  frontend/src/App.jsx
  frontend/src/assets/deleteIcon.svg
  frontend/src/assets/icon.svg
  frontend/src/assets/icon2.png
  frontend/src/components/MainPage.jsx
  frontend/src/components/Plan/CreateMap.jsx
  frontend/src/components/Plan/NewPlan.jsx
  frontend/src/components/Plan/NewPlan.module.css
  frontend/src/components/Plan/PlanNavbar.jsx
  frontend/src/components/Plan/PlanNavbar.module.css
  frontend/src/components/Plan/TravelList.jsx
  frontend/src/components/Plan/TravelList.module.css
  frontend/src/components/UI/Button.jsx
  frontend/src/components/UI/Button.module.css
  frontend/src/components/UI/Navbar.jsx
Labels: FE, Feature, 🚨 우선 순위 높음

#21 20/배포 관련 버그 수정
  frontend/src/App.jsx
Labels: FE, Refactor

#24 5/navbar logic
  frontend/index.html
  frontend/src/App.jsx
  frontend/src/components/MainPage.jsx
  frontend/src/components/MainPage.module.css
  frontend/src/components/UI/Navbar.css
  frontend/src/components/UI/Navbar.jsx
Labels: FE, Refactor

#25 22/모달 UI 임시 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Plan/NewPlan.jsx
  frontend/src/components/Plan/NewPlan.module.css
Labels: FE, Feature

#37 32/비번찾기 페이지 수정 완료
  frontend/src/components/Account/FindPwdForm.jsx
Labels: FE, Feature

#39 38/계획 페이지 상단 바 로직 구현
  frontend/src/assets/editIcon.png
  frontend/src/components/Plan/NewPlan.jsx
  frontend/src/components/Plan/NewPlan.module.css
  frontend/src/components/Plan/PlanNavbar.jsx
  frontend/src/components/Plan/PlanNavbar.module.css
Labels: FE, Feature, 작업중

#45 36/라우터 내용 일부 수정
  frontend/src/App.jsx
  frontend/src/components/Account/Account.jsx
  frontend/src/components/Account/FindPwdForm.jsx
  frontend/src/components/Account/LoginForm.jsx
  frontend/src/components/Account/RegisterForm.jsx
  frontend/src/components/MainPage.jsx
  frontend/src/components/MainPage.module.css
  frontend/src/components/Mypage/Mypage.jsx
  frontend/src/components/Plan/NewPlan.jsx
  frontend/src/components/Plan/useKakaoLoader.jsx
  frontend/src/components/TravelReview/NewReview.jsx
  frontend/src/components/UI/Navbar.css
  frontend/src/components/UI/Navbar.jsx
Labels: FE, Refactor

#46 36/라우팅 오류 해결
  frontend/src/components/MainPage.jsx
  frontend/src/components/Mypage/Mypage.jsx
  frontend/src/components/Plan/NewPlan.jsx
  frontend/src/components/TravelReview/NewReview.jsx
  frontend/src/components/UI/Navbar.jsx
Labels: FE, Refactor

#48 38/모달 창에서 입력한 값 상단바에 동적으로 변경
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Plan/NewPlan.jsx
  frontend/src/components/Plan/NewPlan.module.css
  frontend/src/components/Plan/PlanNavbar.jsx
  frontend/src/components/Plan/PlanNavbar.module.css
  frontend/src/components/Plan/SearchLocation.jsx
  frontend/src/components/UI/ModalComponent.jsx
  frontend/src/components/UI/ModalComponent.module.css
  frontend/src/components/UI/Navbar.jsx
Labels: FE, Feature

#51 50/메인페이지, 네비게이션 바 UI 수정
  frontend/src/components/MainPage.jsx
  frontend/src/components/MainPage.module.css
  frontend/src/components/Plan/CreateMap.jsx
  frontend/src/components/Plan/NewPlan.module.css
  frontend/src/components/Plan/PlanNavbar.module.css
  frontend/src/components/Plan/TravelList.jsx
  frontend/src/components/UI/ModalComponent.jsx
  frontend/src/components/UI/ModalComponent.module.css
  frontend/src/components/UI/Navbar.css
Labels: FE, Refactor

#53 52/로그인 관련 페이지 UI 수정
  frontend/src/components/Account/AccountForm.css
  frontend/src/components/Account/AccountForm.module.css
  frontend/src/components/Account/FindPwdForm.jsx
  frontend/src/components/Account/LoginForm.jsx
  frontend/src/components/Account/RegisterForm.jsx
Labels: FE, Refactor

#55 54/리뷰페이지와 상세페이지 구현
  frontend/src/assets/arrow_back.svg
  frontend/src/components/TravelReview/ReadReview.jsx
  frontend/src/components/TravelReview/ReadReview.module.css
  frontend/src/components/TravelReview/ReviewList.jsx
  frontend/src/components/TravelReview/ReviewList.module.css
Labels: FE, Feature

#59 15/검색기능 및 리스트 출력 추가
  frontend/index.html
  frontend/src/components/Plan/CreateMap.jsx
  frontend/src/components/Plan/NewPlan.jsx
  frontend/src/components/Plan/NewPlan.module.css
  frontend/src/components/Plan/SearchLocation.jsx
  frontend/src/components/UI/ModalComponent.jsx
Labels: FE, Feature, 🚨 우선 순위 높음, 작업중

#60 15/장소 검색 후 리스트에 추가 구현
  frontend/src/components/Plan/CreateMap.jsx
  frontend/src/components/Plan/NewPlan.jsx
  frontend/src/components/Plan/PlanNavbar.jsx
  frontend/src/components/Plan/TravelList.jsx
  frontend/src/components/UI/ModalComponent.jsx
Labels: FE, Feature, 🚨 우선 순위 높음, 작업중

#63 58/리뷰작성 페이지, 리뷰보는 페이지 및 로그인 관련 페이지 UI 수정
  frontend/index.html
  frontend/src/App.css
  frontend/src/components/Account/AccountForm.module.css
  frontend/src/components/Account/FindPwdForm.jsx
  frontend/src/components/Account/LoginForm.jsx
  frontend/src/components/Account/RegisterForm.jsx
  frontend/src/components/TravelReview/NewReview.jsx
  frontend/src/components/TravelReview/NewReview.module.css
  frontend/src/components/TravelReview/ReadReview.module.css
  frontend/src/components/TravelReview/ReviewList.module.css
Labels: FE, Refactor

#64 15/계획 생성 페이지 기본 로직 완성
  frontend/src/assets/arrowIcon.svg
  frontend/src/components/Plan/CreateMap.jsx
  frontend/src/components/Plan/NewPlan.jsx
  frontend/src/components/Plan/PlanNavbar.jsx
  frontend/src/components/Plan/PlanNavbar.module.css
  frontend/src/components/Plan/SearchLocation.jsx
  frontend/src/components/Plan/TravelList.jsx
  frontend/src/components/Plan/TravelList.module.css
  frontend/src/components/UI/ModalComponent.jsx
Labels: FE, Feature, 🚨 우선 순위 높음

#66 65/NewPlan 페이지 UI 수정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/marker_number_blue.png
  frontend/src/assets/searchIcon.png
  frontend/src/components/Plan/CreateMap.jsx
  frontend/src/components/Plan/NewPlan.jsx
  frontend/src/components/Plan/NewPlan.module.css
  frontend/src/components/Plan/PlanNavbar.jsx
  frontend/src/components/Plan/PlanNavbar.module.css
  frontend/src/components/Plan/TravelList.jsx
  frontend/src/components/Plan/TravelList.module.css
  frontend/src/components/UI/ModalComponent.jsx
  frontend/src/components/UI/ModalComponent.module.css
Labels: FE, Feature, 작업중
